version: "3"

services:
  proxy:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-proxy
    image: proxy-service
    container_name: proxy-services
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_NAME: 'proxy-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:123456@postgres-master/postgres?sslmode=disable
      PG_REP_URL: postgres://postgres:123456@postgres-slave:5432/postgres?sslmode=disable
      GRPC_MAIL_HOST: 'mail'
      GRPC_MAIL_PORT: 5001
    ports:
      - 5000:5000
    depends_on:
      - mail
    networks:
      - mail-network
  mail:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-mail
    image: mail-service
    container_name: mail-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_NAME: 'mail-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:123456@postgres-master:5432/postgres?sslmode=disable
      PG_REP_URL: postgres://postgres:123456@postgres-slave:5432/postgres?sslmode=disable
    ports:
      - 5001:5001
    networks:
      - mail-network
networks:
  mail-network:
    name: mail-network
    external: true
