version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: mail-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
      - POSTGRES_MASTER=postgres-slave
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - mail-network
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: mail-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mail-network
  redis:
    image: redis
    container_name: mail-redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=password
      - REDIS_REPLICATION_mode=master
    ports:
      - 6379:6379
    networks:
      - mail-network
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: mail-redisinsight
    restart: unless-stopped
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - 8001:8001
    networks:
      - mail-network
volumes:
  pg-data: {}
  redis_data: {}
networks:
  mail-network:
    driver: bridge
    name: mail-network