# Step 1: Modules caching
FROM golang:1.21-alpine3.18 as modules

COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

# Step 2: Builder
FROM golang:1.21-alpine3.18 as builder
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app
# RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
RUN go build -tags migrate -o /bin/app ./cmd/mail

# Step 3: Final
FROM scratch

EXPOSE 5007
EXPOSE 5008

# GOPATH for scratch images is /
COPY --from=builder /app/cmd/mail/config.yml /
COPY --from=builder /app/db/migrations /db/migrations
COPY --from=builder /bin/app /app
CMD ["/app"]
