// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"database/sql"
	"time"
)

type MailClient struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	ServerID   int64     `json:"server_id"`
	TemplateID int64     `json:"template_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type MailServer struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Host           string         `json:"host"`
	Port           int64          `json:"port"`
	Username       string         `json:"username"`
	Password       string         `json:"password"`
	Tls            sql.NullString `json:"tls"`
	SkipTls        sql.NullBool   `json:"skip_tls"`
	MaxConnections sql.NullInt64  `json:"max_connections"`
	IdleTimeout    sql.NullInt64  `json:"idle_timeout"`
	Retries        sql.NullInt64  `json:"retries"`
	WaitTimeout    sql.NullInt64  `json:"wait_timeout"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type MailTemplate struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Html      sql.NullString `json:"html"`
	Status    sql.NullString `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
